# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publishedDate',
            new_name='publishDate',
        ),
    ]
