# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20171015_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='post',
            name='person',
            field=models.CharField(max_length=120, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publishDate',
            field=models.DateTimeField(verbose_name='Tarih'),
        ),
    ]
